output: standalone
images:
  dangerouslyAllowSVG: true
  remotePatterns:
    - protocol: https
      hostname: api.dicebear.com
    - protocol: https
      hostname: images.unsplash.com
    - protocol: http
      hostname: localhost
allowedDevOrigins:
  - "192.168.5.180" # local network
  - "www.example.com" # example.com
  - "127.0.0.1" # localhost
  - "localhost" # localhost
experimental:
  proxyTimeout: 10000
proxy:
  enabled: true
  backendUrl: "http://localhost:8080"
  source: "/api/v1/:path*"
  destinationPattern: "/api/v1/:path*"
