server:
  port: 8080
  mode: debug

database:
  host: localhost
  port: 5432
  user: caoyang
  password: postgres
  dbname: tiny_forum
  sslmode: disable
  timezone: Asia/Shanghai

jwt:
  secret: "tiny-forum-secret-change-in-production-32chars"
  expire: 72h

log:
  level: "debug"
  filename:   "logs/app.log"
  max_size:   100
  max_backups: 10
  max_age:     30
  compress:   true
  console:    true
  json_format: false