# ============================================
# Module 6: Frontend Setup
# ============================================

# 生成前端配置文件（Next.js 风格）
write_frontend_yaml() {
    local backend_url=$1
    local frontend_port=$2
    local local_ip=$3
    local config_dir="frontend"
    local config_file="$config_dir/config.yml"
    
    # 构建 allowed_dev_origins 列表（包含 localhost、本机 IP 等）
    cat > "$config_file" << EOF
# Frontend Configuration (Next.js)
# Generated by TinyForum setup script
# DO NOT EDIT MANUALLY - Run 'make init-dev' to regenerate

output: standalone

images:
  dangerously_allow_svg: true
  remote_patterns:
    - protocol: https
      hostname: api.dicebear.com
    - protocol: https
      hostname: images.unsplash.com
    - protocol: http
      hostname: localhost

allowed_dev_origins:
  - "$local_ip"
  - "127.0.0.1"
  - "localhost"
  # 可以在此添加更多允许的源

experimental:
  proxy_timeout: 10000

proxy:
  enabled: true
  backend_url: "$backend_url"
  source: "/api/v1/:path*"
  destination_pattern: "/api/v1/:path*"
EOF
    
    echo -e "${GREEN}   📝 Frontend configuration saved to $config_file${NC}"
}

setup_frontend() {
    echo ""
    echo "Step 3: Setting up Frontend..."
    
    # 生成前端配置文件（使用全局变量 BACKEND_URL, FRONTEND_PORT, LOCAL_IP）
    local backend_url="${BACKEND_URL:-http://localhost:8080}"
    local frontend_port="${FRONTEND_PORT:-3000}"
    local local_ip="${LOCAL_IP:-localhost}"
    
    write_frontend_yaml "$backend_url" "$frontend_port" "$local_ip"
    
    # 进入前端目录安装依赖
    cd frontend
    
    if [ ! -f "package.json" ]; then
        echo -e "${RED}❌ package.json not found in frontend/ directory.${NC}"
        exit 1
    fi
    
    echo "  Installing dependencies with $PACKAGE_MANAGER..."
    if [ "$PACKAGE_MANAGER" = "pnpm" ]; then
        pnpm install
    else
        npm install
    fi
    echo -e "${GREEN}  Frontend dependencies installed.${NC}"
    
    cd ..
    
    echo -e "${GREEN}✅ Frontend setup completed!${NC}"
    echo "   Configuration: frontend/config.yml"
    echo "   Start command: cd frontend && $PACKAGE_MANAGER run dev"
}