#!/bin/bash

# 连接测试
# REDISCLI_AUTH='tf@password' redis-cli --user tinyforum PING

# ============================================
# Module 4: Redis Management
# ============================================

# 颜色（若未定义则补全）
if [ -z "${RED}" ]; then
    RED='\033[0;31m'
    GREEN='\033[0;32m'
    YELLOW='\033[0;33m'
    NC='\033[0m'
fi

# 检查 Redis 是否运行（无认证）
check_redis_running() {
    if command -v redis-cli >/dev/null 2>&1 && redis-cli ping >/dev/null 2>&1; then
        return 0
    fi
    return 1
}

# 使用特定用户认证后 ping
connect_redis() {
    local username=$1
    local password=$2
    if [ -n "$username" ] && [ -n "$password" ]; then
        redis-cli --user "$username" --pass "$password" ping >/dev/null 2>&1
    else
        redis-cli ping >/dev/null 2>&1
    fi
}

# 检查 Redis 用户是否存在（需要管理员权限）
# 参数: admin_username admin_password target_username
redis_user_exists() {
    local admin_user=$1
    local admin_pass=$2
    local target_user=$3
    # 使用管理员用户执行 ACL GETUSER
    redis-cli --user "$admin_user" --pass "$admin_pass" ACL GETUSER "$target_user" 2>/dev/null | grep -q '"flags"'
}

# 创建 Redis 用户（需要管理员权限）
create_redis_user() {
    local admin_user=$1
    local admin_pass=$2
    local new_user=$3
    local new_pass=$4
    redis-cli --user "$admin_user" --pass "$admin_pass" \
        ACL SETUSER "$new_user" on ">$new_pass" ~* +@all >/dev/null 2>&1
}

# 测试最终用户连接
test_redis_connection() {
    local username=$1
    local password=$2
    redis-cli --user "$username" --pass "$password" PING >/dev/null 2>&1
}

# 导出 Redis YAML 配置
write_redis_yaml() {
    local host=$1
    local port=$2
    local user=$3
    local password=$4
    local config_dir="backend/config"
    local config_file="$config_dir/redis.yml"

    mkdir -p "$config_dir"
    cat > "$config_file" << EOF
# Redis Configuration
# Generated by TinyForum setup script
host: $host
port: $port
user: $user
password: $password
EOF
    echo -e "${GREEN}   📝 Configuration saved to $config_file${NC}"
}

# 主函数：设置 Redis 用户及连接
setup_redis() {
    local redis_host="${REDIS_HOST:-localhost}"
    local redis_port="${REDIS_PORT:-6379}"
    local default_user="${REDIS_USER:-tinyforum}"
    local default_pass="${REDIS_PASSWORD:-tf@password}"
    local admin_user=""
    local admin_pass=""

    echo ""
    echo "Step: Checking Redis..."

    # 1. 确保 redis-cli 存在
    if ! command -v redis-cli >/dev/null 2>&1; then
        echo -e "${RED}❌ redis-cli not found. Please install Redis client.${NC}"
        exit 1
    fi

    # 2. 检查 Redis 服务是否运行
    if ! check_redis_running; then
        echo -e "${RED}❌ Redis is not running${NC}"
        echo "   Please start Redis:"
        case "$OS" in
            Darwin*)  echo "   - macOS: brew services start redis" ;;
            Linux*)   echo "   - Linux: sudo systemctl start redis" ;;
            MINGW*|MSYS*|CYGWIN*) echo "   - Windows: net start redis" ;;
            *)        echo "   - Run: redis-server" ;;
        esac
        exit 1
    fi
    echo -e "${GREEN}✅ Redis is running${NC}"

    # 3. 确定管理员用户（优先使用 default 无密码，否则尝试环境变量）
    if connect_redis "" ""; then
        admin_user="default"
        admin_pass=""
        echo -e "${GREEN}   Using default Redis admin (no password)${NC}"
    elif [ -n "$REDIS_ADMIN_USER" ] && [ -n "$REDIS_ADMIN_PASS" ] && connect_redis "$REDIS_ADMIN_USER" "$REDIS_ADMIN_PASS"; then
        admin_user="$REDIS_ADMIN_USER"
        admin_pass="$REDIS_ADMIN_PASS"
        echo -e "${GREEN}   Using admin user: $admin_user${NC}"
    else
        echo -e "${RED}❌ Cannot connect to Redis as admin. Please ensure Redis is accessible.${NC}"
        exit 1
    fi

    # 4. 检查目标用户是否存在，不存在则创建
    if redis_user_exists "$admin_user" "$admin_pass" "$default_user"; then
        echo -e "${GREEN}   Redis user '$default_user' already exists${NC}"
    else
        echo "   Creating Redis user '$default_user'..."
        if create_redis_user "$admin_user" "$admin_pass" "$default_user" "$default_pass"; then
            echo -e "${GREEN}   Redis user '$default_user' created${NC}"
        else
            echo -e "${RED}❌ Failed to create Redis user '$default_user'${NC}"
            exit 1
        fi
    fi

    # 5. 测试最终用户连接
    echo "   Testing connection with user '$default_user'..."
    if test_redis_connection "$default_user" "$default_pass"; then
        echo -e "${GREEN}✅ Successfully connected to Redis as '$default_user'${NC}"
    else
        echo -e "${RED}❌ Failed to authenticate as '$default_user'${NC}"
        exit 1
    fi


    # 7. 可选创建额外用户
    echo ""
    read -p "Create an additional Redis user? (y/n): " -n 1 -r
    echo
    if [[ $REPLY =~ ^[Yy]$ ]]; then
        read -p "Enter additional username: " extra_user
        read -sp "Enter password for $extra_user: " extra_pass
        echo
        if create_redis_user "$admin_user" "$admin_pass" "$extra_user" "$extra_pass"; then
            echo -e "${GREEN}✅ Additional user '$extra_user' created${NC}"
            read -p "Grant full access? (y/n): " -n 1 -r
            echo
            if [[ $REPLY =~ ^[Yy]$ ]]; then
                # 已经授予过 +@all，所以此处无需再操作
                echo -e "${GREEN}   Full privileges granted${NC}"
            else
                # 可自定义权限，这里仅给出提示
                echo "   You can manually set privileges with:"
                echo "     redis-cli --user $admin_user --pass *** ACL SETUSER $extra_user +@read"
            fi
        else
            echo -e "${RED}❌ Failed to create additional user${NC}"
        fi
    fi
    # 6. 导出 YAML 配置
    
    write_redis_yaml "$redis_host" "$redis_port" "$default_user" "$default_pass"

    echo ""
    echo -e "${GREEN}🎉 Redis setup completed!${NC}"
    echo "   Host: $redis_host"
    echo "   Port: $redis_port"
    echo "   User: $default_user"
    echo "   Password: $default_pass"
    echo "   Config file: config/redis.yml"
}