# ============================================
# Module 6: Frontend Setup
# ============================================

write_frontend_yaml() {
    local backend_url="$1"
    local frontend_port="$2"
    local local_ip="$3"
    local config_dir="frontend"
    local config_file="${config_dir}/config.yml"

    mkdir -p "$config_dir"
    cat > "$config_file" << EOF
# Frontend Configuration (Next.js)
# Generated by TinyForum setup script
# DO NOT EDIT MANUALLY — run 'make init-dev' to regenerate

output: standalone

images:
  dangerously_allow_svg: true
  remote_patterns:
    - protocol: https
      hostname: api.dicebear.com
    - protocol: https
      hostname: images.unsplash.com
    - protocol: http
      hostname: localhost

allowed_dev_origins:
  - "${local_ip}"
  - "127.0.0.1"
  - "localhost"

experimental:
  proxy_timeout: 10000

proxy:
  enabled: true
  backend_url: "${backend_url}"
  source: "/api/v1/:path*"
  destination_pattern: "/api/v1/:path*"
EOF
    echo -e "${GREEN}   📝 Saved: ${config_file}${NC}"
}

setup_frontend() {
    echo ""
    echo -e "${BOLD}━━━ Frontend Setup ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"

    local backend_url="${BACKEND_URL:-http://localhost:8080}"
    local frontend_port="${FRONTEND_PORT:-3000}"
    local local_ip="${LOCAL_IP:-localhost}"

    write_frontend_yaml "$backend_url" "$frontend_port" "$local_ip"

    # Bug fix: 用子 shell 隔离 cd，避免影响父进程工作目录
    (
        cd "$PROJECT_ROOT/frontend" || {
            echo -e "${RED}❌ 'frontend' directory not found under PROJECT_ROOT${NC}"
            exit 1
        }

        if [ ! -f "package.json" ]; then
            echo -e "${RED}❌ package.json not found in frontend/.${NC}"
            exit 1
        fi

        echo "   Installing dependencies with ${PACKAGE_MANAGER}..."
        if [ "$PACKAGE_MANAGER" = "pnpm" ]; then
            pnpm install
        else
            npm install
        fi
        echo -e "${GREEN}   ✅ Frontend dependencies installed.${NC}"
    ) || return 1

    echo -e "${GREEN}✅ Frontend setup completed.${NC}"
    echo "   Config  : frontend/config.yml"
    echo "   Start   : cd frontend && ${PACKAGE_MANAGER} run dev"
    echo -e "${BOLD}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
}